#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.a8fc345c02ab555501d555cdd921871a8a89ccf9.name = "0.8.0"
